language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
cache:
  directories:
    - vendor
matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
sudo: false
before_script:
  - composer install --prefer-source --no-interaction --dev
script: composer test
